
services:

  nginx:
    image: nginx:1.29.7-alpine
    container_name: ${COMPOSE_NAME:-app}_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh
      
      - ./data/nginx/log/:/var/log/nginx
      - ./data/nginx/sites/:/usr/share/nginx/html

      - ./data/certbot/conf:/etc/nginx/ssl
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    entrypoint: ["/bin/sh", "/etc/nginx/entrypoint.sh"]

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"