server{
    listen 443;
    server_name <>;

    include /etc/nginx/conf.d/ssl.conf;

    include /etc/nginx/conf.d/deny.conf;

    location / {
        include /etc/nginx/conf.d/proxy-base.conf;
        proxy_pass http://api_servers;
    }
}
