server {
    listen 443 ssl;
    server_name <>;

    include /etc/nginx/conf.d/ssl.conf;

    include /etc/nginx/conf.d/deny.conf;

    # Basic auth
    include /etc/nginx/conf.d/basic-auth.conf; 

    location / {
        include /etc/nginx/conf.d/proxy.conf;
        proxy_pass http://servers;
    }
}
