
server{
    listen 443 ssl;
    server_name <>;

    include /etc/nginx/conf.d/ssl.conf;

    include /etc/nginx/conf.d/deny.conf;

    location / {
        root /usr/share/nginx/html/<>;
        try_files $uri $uri/ /index.html;
    }
}
