user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main escape=json  '[$time_iso8601]    '
                        'IP="$remote_addr"    '
                        'Host="$host"    '
                        'Status=$status    '
                        'URL="$request"    '
                        'Bytes-Sent=$body_bytes_sent    '
                        'Body="$request_body"    '
                        'Referer="$http_referer"    '
                        'User-Agent="$http_user_agent"    '
                        'User="$remote_user"    '
                        'X-Forward-For="$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    client_max_body_size 100M;

    gzip on;               # enable gzip
    gzip_http_version 1.1; # turn on gzip for http 1.1 and higher
    gzip_disable "msie6";  # IE 6 had issues with gzip
    gzip_comp_level 5;     # inc compresion level, and CPU usage
    gzip_min_length 100;   # minimal weight to gzip file
    gzip_proxied any;      # enable gzip for proxied requests (e.g. CDN)
    gzip_buffers 16 8k;    # compression buffers (if we exceed this value, disk will be used instead of RAM)
    gzip_vary on;          # add header Vary Accept-Encoding (more on that in Caching section)


    gzip_types text/plain;
    gzip_types text/css;
    gzip_types application/javascript;
    gzip_types application/json;
    gzip_types application/vnd.ms-fontobject;
    gzip_types application/x-font-ttf;
    gzip_types font/opentype;
    gzip_types image/svg+xml;
    gzip_types image/x-icon;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/conf.d/servers/*.conf;
}